name: Trigger auto deployment for php-apache-mysql-01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/php-apache-mysql-01-AutoDeployTrigger-9af622a6-df3b-4531-8dea-e6e3717d1042.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PHPAPACHEMYSQL01_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PHPAPACHEMYSQL01_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PHPAPACHEMYSQL01_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: nicecontainerreg.azurecr.io
          registryUsername: ${{ secrets.PHPAPACHEMYSQL01_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PHPAPACHEMYSQL01_REGISTRY_PASSWORD }}
          containerAppName: php-apache-mysql-01
          resourceGroup: rg-nh-test-01
          imageToBuild: nicecontainerreg.azurecr.io/php-apache-mysql-01:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


